### PR TITLE
Add extra methods for authentication and management of users

### PR DESCRIPTION
**Pull request by martinjhm271**
- Add method for create email/password user
- Add method that generates the email action link for sign-in flows, using the action code settings provided

### CODE REVIEW

**Comment by nitinstp23** [comment]
@martinjhm Can you add some tests for these functions? - 

`create_email_password_user` & `generate_sign_in_with_email_link `

Also update the README file.

**Comment by martinjhm271** [comment]
> @martinjhm Can you add some tests for these functions? -
> 
> `create_email_password_user` & `generate_sign_in_with_email_link `
> 
> Also update the README file.

Sure, No problem

**Comment by martinjhm271** [comment]
@nitinstp23 Done.

**Comment by nitinstp23** [comment]
@martinjhm Thanks! ❤️ 💙 💚 💛 💜

**Comment by nitinstp23** [comment]
@martinjhm Can you fix the failing tests in master?

https://travis-ci.org/scripbox/firebase-admin-ex/builds/541131441

**Pull request merged**
