### PR TITLE
Add simple dynamic link implementation

### PR DESCRIPTION
**Pull request by bernardd**
This adds some basic support for using Firebase's dynamic link generator and shortener.

### CODE REVIEW

**Comment by bernardd** [comment]
@nitinstp23 Is there anything I can do to help get this merged in? I'd like to be using the official hex repo rather than our own fork if possible.

**Comment by nitinstp23** [comment]
@bernardd Sorry for the late response. The PR looks good 👍

**Comment by nitinstp23** [comment]
❤️ 💙 💚 💛 💜

**Comment by martinjhm271** [comment]
I make a PR :+1:

**Pull request merged**
